### ISSUE TITLE
Adding 7TV emotes unexpected status: 403 

### ISSUE THREAD

**Issue by badoge** [gempir/gempbot#33]
Bot has been failing to add 7TV emotes for a while now

⚠ ️ Failed to add 7tv emote from @... response error for https://api.7tv.app/v2/gql: unexpected status: 403

**Comment by gempir** [comment]
Hmm how recent was this? 

I just tested it and it seems to work fine 
![image](https://user-images.githubusercontent.com/9765622/182676546-ad30d460-ad78-43b9-86a1-cb29e1ef3eb4.png)

**Comment by gempir** [comment]
Although I see sometimes in other chats it does seem to fail but with a different error

![image](https://user-images.githubusercontent.com/9765622/182676756-a36fb511-4634-41a6-a582-11389eca67cc.png)

That error means it can't find the emote somehow. Weird.

**Comment by gempir** [comment]
I think I mostly fixed the error I listed. 

Sometimes we just fail to fetch emotes to announce them in chat, but that's not critical.
https://github.com/gempir/gempbot/commit/4e394db10b0c9fcdc857d97768908e27d27c8585

I can't really debug your error without further context.
How to reproduce? What chat did it happen in? What time did it happen?

**Comment by badoge** [comment]
https://logs.ivr.fi/?channel=nam______________________&username=gempbot

**Comment by gempir** [comment]
ERROR: 704620 No Space Available: This set does not have enough slots 
 
 Manually doing it: 
 
 
![image](https://user-images.githubusercontent.com/9765622/182926205-22256242-c6d8-403a-8189-a6476851b06d.png)


:shrug: You gotta check with 7tv

**Comment by badoge** [comment]
The problem was very dank ![1](https://user-images.githubusercontent.com/18620902/182931821-49ce2b68-3a5b-46a7-97d3-f66e483abd00.png) i'll post how i fixed it here incase someone gets the same issue 

I first had to unlink discord from https://next.7tv.app because it was using a different emote set than twitch and taking up more slots than the limit

Then I had to find and remove a deleted emote that only showed up on https://next.7tv.app so adding from the old site you would see that you have an empty slot but it was actually taken up by a deleted emote
