### ISSUE TITLE
Page looks scuffed when there's no data

### ISSUE THREAD

**Issue by ALazyMeme** [gempir/gempbot#35]
![image](https://user-images.githubusercontent.com/12804673/192751885-dbb097fb-4ca3-4063-9c6a-1a1c62d8d84c.png)

**Comment by gempir** [comment]
Looks fine to me, what’s your issue with it

**Comment by ALazyMeme** [comment]
> Looks fine to me, what’s your issue with it 

The columns seem extremely compact, doesn't look right

**Comment by gempir** [comment]
Unscuffed 
![image](https://user-images.githubusercontent.com/9765622/194765446-e5184657-9949-4348-bb43-de899e193b09.png)
