### ISSUE TITLE
Election

### ISSUE THREAD

**Issue by gempir** [gempir/gempbot#46]
An emote system where emotes get voted in over several days. 

Maybe it could work like this:

3 Emotes per day should be added. Viewers get to suggest emotes and vote on suggestions on that day. 

At the End of the Day the top 3 emotes will be added. 

A new voting starts

Checklist:

- [x] emote blocks
- [x] UI to block emotes
- [x] Vote on Website
- [x] Think about Double Nominations

**Comment by hotbear1110** [comment]
Imo voting should be free, but nominating should then costs. Maybe you should be able to vote more than once with points.

**Comment by hotbear1110** [comment]
For moderation, it would be good with a button on the nomination page for blocking/removing emotes. Maybe a system for banning users from nominating also?

**Comment by DaGaugl** [comment]
Make it so that you cant nominate/vote for your emote several times or smth idk

**Comment by gempir** [comment]
First implementation in https://github.com/gempir/gempbot/pull/47

Above suggestions are not in there yet. But I will look at them the next days and add something like it. 
Voting and Emote Blocks being highest on my list of priorities.

**Comment by gempir** [comment]
- Edge cases of emotes that are already added to the channel --> Generally how to handle failures?

**Comment by gempir** [comment]
You can now:

- Vote on website
- Double nominations just count as a vote (but each user can only vote once, if you do it more than once you get scammed on points Nime)
- Blocked Emotes are respected

**Comment by gempir** [comment]
Button added to directly block an emote and remove it from an election.
