### ISSUE TITLE
History of recently added emotes through nominations

### ISSUE THREAD

**Issue by melon095** [gempir/gempbot#51]
As the title says, gempbot should have a second list on the website which displays recently added emotes through nominations. Extra information could be shown such as who added the emote and how many votes it got in total.

You could expand on this to display when this emote will be removed, if nominations has a separate emote rotation outside of the  channel point redemptions system.

**Comment by gempir** [comment]
This is a pain in the ass and just a lot of useless data to keep which will almost never be looked at again. 
I don't really wanna implement this.

**Comment by gempir** [comment]
Other bots already provide a very similar feature of listing changed emotes.

**Comment by gempir** [comment]
Nymn wants it

**Comment by gempir** [comment]
There is a history now https://bot-api.gempir.com/api/emotelog?channel=nymn
