### ISSUE TITLE
The bot added the wrong emotes

### ISSUE THREAD

**Issue by hotbear1110** [gempir/gempbot#59]
The bot added the wrong emotes
https://bot-api.gempir.com/api/emotelog?channel=nymn

MILK and uhoh were added.
should have been dankHug, docLeave and pepeLaugh

![image](https://user-images.githubusercontent.com/77441913/211069414-dd3ba81a-07a5-40a1-85c9-cf6a515a3e98.png)

![image](https://i.imgur.com/iGwQc92.png)

**Comment by gempir** [comment]
Should be fixed with d6b08ef5f1da24205a8b91549dedbdac86667ea5 and now it properly skips over emotes that are banned or can't be added and just adds the next one in the list.
